all:
  hosts:
    web1:
      ansible_host: 10.0.0.4 # A remplacer par l'IP de votre machine cible ou le nom de domaine
      ansible_user: admin 
      ansible_password: admin 
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    web2:
      ansible_host: 10.0.0.5 # A remplacer par l'IP de votre machine cible ou le nom de domaine
      ansible_user: admin 
      ansible_password: admin 
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
