---
- name: "Apache installation using Docker"
  hosts: prod
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Utiliser Python 3
  pre_tasks:
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install Python 3 pip
      yum:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: /usr/bin/pip3  # Utiliser pip3 pour Python 3

  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Create Apache container
      community.docker.docker_container:  # Utiliser la collection Docker d'Ansible
        name: webapp
        image: httpd
        ports:
          - "80:80"
